#===============================================[ Notes ]================================================#
# name: SmartTournament                                                                                  #
# author: Hid                                                                                            #
# version: 1.0                                                                                           #
#========================================================================================================#

configuration:
   tournament_delay: 120

messages:
    prefix: "&4Tournament &8//&a "
    no-permission: "&cYou do not have permission to execute this command."
    improper-usage: "&cImproper usage. Proper usage for this command: /tournament join | leave | start | end | setspawn <arena> <num> | setspawn spectator."
    invalid-sender: "&cInvalid sender. You must be a player to perform this command."
    invalid-number: "&cInvalid number. You must enter a positive integer."
    severe-error: "&cSevere error. Please contact an administrator."
    no-tournaments-running: "&cThere are currently no tournaments running."
    tournament-already-started: "&cThe tournament has already started."
    already-in-tournament: "&cYou are already in the tournament."
    not-enough-players: "&eThere are not enough players for this tournament to start."
    joined-tournament-success: "&aYou have successfully joined the tournament."
    not-in-tournament: "&cYou are currently not in a tournament."
    left-tournament-success: "&aYou have successfully left the tournament."
    tournament-areas-not-set: "&cThe spectator or arena areas are not set."
    spectator-area-set: "&aYou have successfully set the spectator area."
    tournament-start-success: "&aYou have successfully started the tournament."
    tournament-start-broadcast: "&eA tournament has just started! Type /tournament join to join the tournament."
    tournament-end-success: "&aYou have successfully ended the tournament."
    tournament-end-broadcast: "&eThe tournament has forcibly been ended."
    tournament-end-error: "&cThe tournament has ended due to an error."
    match-idle-broadcast: "&a{initiator}&7 and &a{opponent} &7have both been eliminated for idling."
    arena-invalid-position: "&cInvalid number. You must enter either 1 or 2 for the position."
    arena-set-success: "&aYou have successfully set the arena: {arena}."
spectator:

arenas:


