#===============================================[ Notes ]================================================#
# name: SmartTournament                                                                                  #
# author: Hid                                                                                            #
# version: 1.0                                                                                           #
#========================================================================================================#

configuration:
   tournament_delay: 120

messages:

spectator:

arenas:


